### ISSUE TITLE
JarClassLoader: Warning: Null manifest from input stream associated with: lib/android.jar

### ISSUE THREAD

**Issue by lshAndroid** [hzw1199/xml2axml#1]
无法正常使用啊,有没有详细的教程

**Comment by lshAndroid** [comment]
java -jar D:\nxtool\xml2axml.jar D:\apknx\yybpack\AndroidManifest.xml D:\AndroidManifest.xml

JarClassLoader: Warning: Null manifest from input stream associated with: lib/android.jar

**Comment by hzw1199** [comment]
Refer to README.md to learn how to use

* encode  
```
java -jar xml2axml e [AndroidManifest-readable-in.xml] [AndroidManifest-bin-out.xml]
```
* decode  
```
java -jar xml2axml d [AndroidManifest-bin-in.xml] [AndroidManifest-readable-out.xml]
```

So you forgot to use ```e``` or ```d```.

**Comment by ngoalong123** [comment]
> Refer to README.md to learn how to use
> 
> * encode
> 
> ```
> java -jar xml2axml e [AndroidManifest-readable-in.xml] [AndroidManifest-bin-out.xml]
> ```
> 
> * decode
> 
> ```
> java -jar xml2axml d [AndroidManifest-bin-in.xml] [AndroidManifest-readable-out.xml]
> ```
> 
> So you forgot to use `e` or `d`.

I follow README.md but it not work. it always show "JarClassLoader: Warning: Null manifest from input stream associated with: lib/android.jar"

MY CMD: "java -jar xml2axml.jar d D:\AndroidManifest.xml D:\abc.xml"

**Comment by EastWoodYang** [comment]
也出现同样问题，修改后的AndroidManifest.xml，也无法通过AXMLPrinter正常打印，会报错

**Comment by p01arbear** [comment]
Convertation works for me despite the warning.

**Comment by hzw1199** [comment]
@lshAndroid @ngoalong123 @EastWoodYang 
Hey, try the new release 1.1.0!
The problem should have bean fixed!
